### load
GET localhost:5000/api/word/17370258481252573

### 分页
GET localhost:5000/api/word?page=1&size=10

### 新增
POST localhost:5000/api/word
Content-Type: application/json

{
  "chnName": "id",
  "engName": "id",
  "engAbbr": "id",
  "stdWordFlag": true
}

### 修改
PUT localhost:5000/api/word/17370258481252573
Content-Type: application/json

{
  "chnName": "id",
  "engName": "id",
  "engAbbr": "id"
}

### 删除
DELETE localhost:5000/api/word/17370258481252573